# Generated by Django 5.2.17 on 2026-09-11 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InternalRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('external_ref', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('remote_addr', models.CharField(blank=True, default='', max_length=64)),
                ('response_status', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_internal_request_log',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['external_ref', 'created_at'], name='billing_int_externa_127ca4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_ref', models.CharField(max_length=255, unique=True)),
                ('patient_email', models.EmailField(max_length=254)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('failed', 'Failed'), ('void', 'Void'), ('refunded', 'Refunded')], default='draft', max_length=16)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('provider_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('amount_refunded_cents', models.PositiveIntegerField(default=0)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'billing_invoice',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='billing_inv_status_bfbaa4_idx'), models.Index(fields=['patient_email'], name='billing_inv_patient_1a81eb_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='billing_invoice_amount_positive'), models.CheckConstraint(condition=models.Q(('amount_refunded_cents__lte', models.F('amount_cents'))), name='billing_invoice_refund_within_amount')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'billing_webhook_event',
                'ordering': ('-received_at',),
                'indexes': [models.Index(fields=['status', 'received_at'], name='billing_web_status_bf5c29_idx'), models.Index(fields=['event_type'], name='billing_web_event_t_2dd583_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='billing_webhook_event_unique')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_charge_id', models.CharField(max_length=255, unique=True)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=16)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.invoice')),
            ],
            options={
                'db_table': 'billing_payment',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['invoice', 'status'], name='billing_pay_invoice_a67165_idx')],
            },
        ),
    ]
